"""Compare official card text (data/official_text.json, from Limitless) with
every Twinleaf printing of the same name, to decide which Twinleaf class a
pool printing should use (or that none matches and a class must be written).

usage: compare_official.py   -> data/official_match.json + data/official_match_report.md
"""
import difflib, json, os, re

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
db = json.load(open(os.path.join(ROOT, 'data/official_text.json')))
tl = json.load(open(os.path.join(ROOT, 'data/twinleaf-cards.json')))
pool = {('%s %s' % (r['set'], r['number'])): r for r in json.load(open(os.path.join(ROOT, 'data/pool.json')))}
by_name = {}
for c in tl:
    by_name.setdefault(c.get('name'), []).append(c)
COST = re.compile(r'^[GRWLPFDMCN]+$')
ENERGY_LETTERS = set('grwlpfdmcn')


# Rules and reminder text that one side prints and the other models as a tag or omits.
REMINDERS = [
    r"you may play only 1 supporter card during your turn( \(before your attack\))?\.?",
    r"as long as this pokemon is on your bench, prevent all damage done to this pokemon by attacks \(both yours and your opponent's\) ?\.?",
    r"when your pokemon ex is knocked out, your opponent takes 2 prize cards\.?",
    r"you can't have more than 1 ace spec card in your deck\.?",
    r"you may play any number of item cards during your turn\.?",
    r"attach a pokemon tool to 1 of your pokemon that doesn't already have a pokemon tool attached\.?",
]


def norm(s):
    s = (s or '').lower().replace('pokémon', 'pokemon').replace('’', "'")
    for r in REMINDERS:
        s = re.sub(r, ' ', s)
    s = re.sub(r'\[[a-z]\]|\{[a-z]\}', ' ', s)
    # Energy symbols: Twinleaf writes [G], Limitless a bare G; drop both.
    return ' '.join(w for w in re.findall(r"[a-z0-9']+", s) if w not in ENERGY_LETTERS)


def parse_official(t):
    lines = [l.strip() for l in t.split('\n') if l.strip()]
    # First line is the card name; "- Evolves from" is followed by the pre-evolution's name.
    skip = {0} | {i + 1 for i, l in enumerate(lines) if l.startswith('- Evolves from')}
    hp = re.search(r'(\d+) HP', t)
    attacks, abilities, body = [], [], []
    i = 0
    while i < len(lines):
        l = lines[i]
        if l == 'Ability:' and i + 1 < len(lines):
            abilities.append(lines[i + 1])
            i += 2
            continue
        if COST.match(l) and i + 1 < len(lines):
            m = re.match(r'^(.*?)\s*(\d+[×x+\-]?)?$', lines[i + 1])
            attacks.append((m.group(1).strip(), (m.group(2) or '').rstrip('×x+-')))
            i += 2
            continue
        if i not in skip and not re.match(r'^(Weakness|Resistance|Retreat|- |Pokémon|Trainer|Energy|Item|Supporter|Stadium|Pokémon Tool|ACE SPEC|Tera)', l):
            body.append(l)
        i += 1
    return {'hp': int(hp.group(1)) if hp else None, 'attacks': attacks, 'abilities': abilities, 'text': norm(' '.join(body))}


def tl_sig(c):
    atk = [(a.get('name'), str(a.get('damage') or '')) for a in c.get('attacks') or []]
    pw = [p.get('name') for p in c.get('powers') or []]
    txt = ' '.join([c.get('text') or ''] + [a.get('text') or '' for a in c.get('attacks') or []] + [p.get('text') or '' for p in c.get('powers') or []])
    return {'hp': c.get('hp'), 'attacks': atk, 'abilities': pw, 'text': norm(txt)}


def score(o, s):
    same_atk = [a for a, _ in o['attacks']] == [a for a, _ in s['attacks']]
    same_dmg = [d for _, d in o['attacks']] == [d for _, d in s['attacks']]
    same_ab = o['abilities'] == s['abilities']
    same_hp = o['hp'] == s['hp'] or o['hp'] is None
    a, b = set(o['text'].split()), set(s['text'].split())
    ratio = len(a & b) / len(a | b) if (a or b) else 1.0   # word-set overlap: clause order doesn't matter
    exact = same_atk and same_dmg and same_ab and same_hp and ratio >= 0.85
    return exact, ratio + same_atk + same_dmg + same_ab + same_hp, dict(atk=same_atk, dmg=same_dmg, ab=same_ab, hp=same_hp, text=round(ratio, 2))


out = {}
for key, v in sorted(db.items()):
    o = parse_official(v['text'])
    row = pool.get(key, {})
    cands = []
    for c in by_name.get(v['name'], []):
        exact, sc, why = score(o, tl_sig(c))
        cands.append({'fullName': c['fullName'], 'class': c.get('$class'), 'exact': exact, 'score': round(sc, 2), 'why': why})
    cands.sort(key=lambda x: -x['score'])
    best = cands[0] if cands else None
    verdict = 'no-twinleaf-card' if not cands else ('use ' + best['fullName'] if best['exact'] else 'needs-new-class (closest: %s)' % best['fullName'])
    out[key] = {'name': v['name'], 'current': row.get('fullName'), 'print_match': row.get('print_match') or 'absent',
                'verdict': verdict, 'best': best, 'candidates': cands[:4], 'official': o, 'url': v['url']}
json.dump(out, open(os.path.join(ROOT, 'data/official_match.json'), 'w'), indent=1, ensure_ascii=False)
lines = ['# Official text vs Twinleaf printings', '', 'Generated by `tools/compare_official.py` from Limitless TCG text.', '',
         '| printing | card | now mapped to | verdict |', '|---|---|---|---|']
for key, r in out.items():
    lines.append('| %s | %s | %s | %s |' % (key, r['name'], r['current'] or '—', r['verdict']))
open(os.path.join(ROOT, 'data/official_match_report.md'), 'w').write('\n'.join(lines) + '\n')
import collections
print(collections.Counter(r['verdict'].split(' ')[0] for r in out.values()))
for key, r in out.items():
    print('%-8s %-24s %-28s %s' % (key, r['name'][:24], (r['current'] or '-')[:28], r['verdict'][:70]))
