"""Generate engine/src/gen/cards.rs from the Twinleaf card dump (tier 0).

Every card in the frozen pool (plus basic energy) becomes a static CardDef
with its printed fields copied verbatim from the Twinleaf class instance.
`behavior` names the class in the prototype chain that carries the card's
logic (reduceEffect / canPlay / ...), so reprints share one implementation.
"""
import json, os, re, sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
cards = {c['fullName']: c for c in json.load(open(os.path.join(ROOT, 'data/twinleaf-cards.json')))}
pool = json.load(open(os.path.join(ROOT, 'data/pool.json')))
TAGS = json.load(open(os.path.join(ROOT, 'data/tags.json'))) if os.path.exists(os.path.join(ROOT, 'data/tags.json')) else None

names = []
for r in pool:
    n = r.get('fullName')
    if n and n not in names:
        names.append(n)
extra = [a for a in sys.argv[1:]]
for n in extra:
    if n not in names:
        names.append(n)

LOGIC = {'reduceEffect', 'canPlay', 'canUseFromHandToBench'}


def rs_str(s):
    if s is None:
        return 'None'
    return 'Some(%s)' % json.dumps(s, ensure_ascii=False)


def lit(s):
    return json.dumps(s if s is not None else '', ensure_ascii=False)


def u8s(xs):
    return '&[%s]' % ', '.join(str(int(x)) for x in xs)


def behavior(c):
    for link in c.get('$chain', []):
        if LOGIC & set(link['own']):
            return link['cls']
    return ''


TAG_NAMES = None


def tag_bits(tags):
    bits = 0
    for t in tags:
        bits |= 1 << TAG_NAMES.index(t)
    return bits


src = open(os.path.join(ROOT, 'engine/src/types.rs')).read()
start = src.index('pub const TAG_NAMES')
block = src[src.index('[', start) + 1: src.index('];', start)]
TAG_NAMES = re.findall(r'"([^"]*)"', block)

out = []
out.append('// @generated by tools/gen_carddb.py from data/twinleaf-cards.json. Do not edit.\n')
out.append('use crate::carddb::*;\n\n')
out.append('pub static CARDS: &[CardDef] = &[\n')
for n in names:
    c = cards[n]
    st = c['superType']
    attacks = []
    for a in c.get('attacks') or []:
        flags = []
        for f in ('canUseOnFirstTurn', 'useOnBench', 'gxAttack', 'shredAttack', 'barrage', 'copycatAttack'):
            flags.append('%s: %s' % ({'canUseOnFirstTurn': 'can_use_on_first_turn', 'useOnBench': 'use_on_bench', 'gxAttack': 'gx_attack', 'shredAttack': 'shred_attack', 'barrage': 'barrage', 'copycatAttack': 'copycat_attack'}[f], 'true' if a.get(f) is True else 'false'))
        attacks.append('AttackDef { name: %s, cost: %s, damage: %d, damage_calculation: %s, text: %s, has_effect_fn: %s, %s }' % (
            lit(a['name']), u8s(a['cost']), int(a['damage']), rs_str(a.get('damageCalculation')), lit(a.get('text', '')),
            'true' if isinstance(a.get('effect'), dict) else 'false', ', '.join(flags)))
    powers = []
    for p in c.get('powers') or []:
        fl = []
        for f, rf in (('useWhenInPlay', 'use_when_in_play'), ('useFromHand', 'use_from_hand'), ('useFromHandToBench', 'use_from_hand_to_bench'),
                      ('useFromDiscard', 'use_from_discard'), ('exemptFromAbilityLock', 'exempt_from_ability_lock'), ('exemptFromInitialize', 'exempt_from_initialize'),
                      ('abilityLock', 'ability_lock'), ('barrage', 'barrage'), ('knocksOutSelf', 'knocks_out_self'), ('isFossil', 'is_fossil')):
            fl.append('%s: %s' % (rf, 'true' if p.get(f) is True else 'false'))
        powers.append('PowerDef { name: %s, power_type: %d, text: %s, has_effect_fn: %s, %s }' % (
            lit(p['name']), int(p['powerType']), lit(p.get('text', '')), 'true' if isinstance(p.get('effect'), dict) else 'false', ', '.join(fl)))
    weak = ', '.join('Weakness { card_type: %d, value: %s }' % (w['type'], ('Some(%d)' % w['value']) if w.get('value') is not None else 'None') for w in c.get('weakness') or [])
    res = ', '.join('Resistance { card_type: %d, value: %d }' % (w['type'], w['value']) for w in c.get('resistance') or [])
    fields = [
        'full_name: %s' % lit(c['fullName']),
        'name: %s' % lit(c['name']),
        'set: %s' % lit(c['set']),
        'set_number: %s' % lit(str(c.get('setNumber', ''))),
        'class: %s' % lit(c['$class']),
        'behavior: %s' % lit(behavior(c)),
        'super_type: %d' % st,
        'regulation_mark: %s' % lit(c.get('regulationMark') or ''),
        'tags: %d' % tag_bits(c.get('_tags') or []),
        'tag_names: &[%s]' % ', '.join(lit(t) for t in c.get('_tags') or []),
        'retreat: %s' % u8s(c.get('retreat') or []),
        'attacks: &[%s]' % ', '.join(attacks),
        'powers: &[%s]' % ', '.join(powers),
        'card_type: %s' % u8s(c.get('cardType') or []),
        'stage: %d' % int(c.get('stage') or 0),
        'hp: %d' % int(c.get('hp') or 0),
        'weakness: &[%s]' % weak,
        'resistance: &[%s]' % res,
        'evolves_from: %s' % lit(c.get('evolvesFrom') or ''),
        'evolves_to: &[%s]' % ', '.join(lit(x) for x in c.get('evolvesTo') or []),
        'evolves_to_stage: %s' % u8s(c.get('evolvesToStage') or []),
        'evolves_from_base: &[%s]' % ', '.join(lit(x) for x in c.get('evolvesFromBase') or []),
        'max_tools: %d' % int(c.get('maxTools') or 1),
        'trainer_type: %d' % int(c.get('trainerType') or 0),
        'first_turn: %s' % ('true' if c.get('firstTurn') else 'false'),
        'attaches_to_opponents_pokemon: %s' % ('true' if c.get('attachesToOpponentsPokemon') else 'false'),
        'energy_type: %d' % int(c.get('energyType') or 0),
        'provides: %s' % u8s(c.get('provides') or []),
        'methods: &[%s]' % ', '.join(lit(m) for m in c.get('$methods') or []),
    ]
    out.append('    CardDef { %s },\n' % ', '.join(fields))
out.append('];\n')
path = os.path.join(ROOT, 'engine/src/gen/cards.rs')
open(path, 'w').write(''.join(out))
print('generated', len(names), 'cards ->', path)
