"""Generate the engine's card database (engine/src/gen/) from data/cards.json.

data/cards.json maps each card's international key ("<Name> <SET> <NUM>") to
its printed fields; the order of the file is the order of the card ids, so
new cards are appended at the end. Every key of data/pool.json is in it, plus
older printings and the pre-evolutions the pool needs (data/support_cards.json).
`behavior` names the class that carries the card's logic, so reprints share
one implementation. data/evolutions.json holds the (name, evolves-from) pairs
of every Stage 1 / non-Basic Pokémon card for cards like Rare Candy that look
past the pool.

usage: gen_carddb.py   -> engine/src/gen/{cards,stage1,evolutions}.rs
"""
import json, os

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
cards = json.load(open(os.path.join(ROOT, 'data/cards.json')))
evolutions = json.load(open(os.path.join(ROOT, 'data/evolutions.json')))
GEN = os.path.join(ROOT, 'engine/src/gen')


def rs_str(s):
    if s is None:
        return 'None'
    return 'Some(%s)' % json.dumps(s, ensure_ascii=False)


def lit(s):
    return json.dumps(s if s is not None else '', ensure_ascii=False)


def u8s(xs):
    return '&[%s]' % ', '.join(str(int(x)) for x in xs)


def b(v):
    return 'true' if v else 'false'


def tag_bits(tags, tag_names):
    bits = 0
    for t in tags:
        bits |= 1 << tag_names.index(t)
    return bits


import re
src = open(os.path.join(ROOT, 'engine/src/types.rs')).read()
start = src.index('pub const TAG_NAMES')
block = src[src.index('[', start) + 1: src.index('];', start)]
TAG_NAMES = re.findall(r'"([^"]*)"', block)

ATTACK_FLAGS = (('canUseOnFirstTurn', 'can_use_on_first_turn'), ('useOnBench', 'use_on_bench'), ('gxAttack', 'gx_attack'),
                ('shredAttack', 'shred_attack'), ('barrage', 'barrage'), ('copycatAttack', 'copycat_attack'))
POWER_FLAGS = (('useWhenInPlay', 'use_when_in_play'), ('useFromHand', 'use_from_hand'), ('useFromHandToBench', 'use_from_hand_to_bench'),
               ('useFromDiscard', 'use_from_discard'), ('exemptFromAbilityLock', 'exempt_from_ability_lock'),
               ('exemptFromInitialize', 'exempt_from_initialize'), ('abilityLock', 'ability_lock'), ('barrage', 'barrage'),
               ('knocksOutSelf', 'knocks_out_self'), ('isFossil', 'is_fossil'))

out = ['// @generated by tools/gen_carddb.py from data/cards.json. Do not edit.\n',
       'use crate::carddb::*;\n\n',
       'pub static CARDS: &[CardDef] = &[\n']
for key, c in cards.items():
    attacks = []
    for a in c['attacks']:
        flags = ', '.join('%s: %s' % (rf, b(a.get(f))) for f, rf in ATTACK_FLAGS)
        attacks.append('AttackDef { name: %s, cost: %s, damage: %d, damage_calculation: %s, text: %s, has_effect_fn: %s, %s }' % (
            lit(a['name']), u8s(a['cost']), a['damage'], rs_str(a.get('damageCalculation')), lit(a.get('text', '')), b(a.get('hasEffectFn')), flags))
    powers = []
    for p in c['powers']:
        flags = ', '.join('%s: %s' % (rf, b(p.get(f))) for f, rf in POWER_FLAGS)
        powers.append('PowerDef { name: %s, power_type: %d, text: %s, has_effect_fn: %s, %s }' % (
            lit(p['name']), p['powerType'], lit(p.get('text', '')), b(p.get('hasEffectFn')), flags))
    weak = ', '.join('Weakness { card_type: %d, value: %s }' % (w['type'], ('Some(%d)' % w['value']) if w.get('value') is not None else 'None') for w in c['weakness'])
    res = ', '.join('Resistance { card_type: %d, value: %d }' % (w['type'], w['value']) for w in c['resistance'])
    fields = [
        'full_name: %s' % lit(key),
        'name: %s' % lit(c['name']),
        'set: %s' % lit(c['set']),
        'set_number: %s' % lit(c['setNumber']),
        'class: %s' % lit(c['class']),
        'behavior: %s' % lit(c['behavior']),
        'super_type: %d' % c['superType'],
        'regulation_mark: %s' % lit(c['regulationMark']),
        'tags: %d' % tag_bits(c['tags'], TAG_NAMES),
        'tag_names: &[%s]' % ', '.join(lit(t) for t in c['tags']),
        'retreat: %s' % u8s(c['retreat']),
        'attacks: &[%s]' % ', '.join(attacks),
        'powers: &[%s]' % ', '.join(powers),
        'card_type: %s' % u8s(c['cardType']),
        'stage: %d' % c['stage'],
        'hp: %d' % c['hp'],
        'weakness: &[%s]' % weak,
        'resistance: &[%s]' % res,
        'evolves_from: %s' % lit(c['evolvesFrom']),
        'evolves_to: &[%s]' % ', '.join(lit(x) for x in c['evolvesTo']),
        'evolves_to_stage: %s' % u8s(c['evolvesToStage']),
        'evolves_from_base: &[%s]' % ', '.join(lit(x) for x in c['evolvesFromBase']),
        'max_tools: %d' % c['maxTools'],
        'trainer_type: %d' % c['trainerType'],
        'first_turn: %s' % b(c['firstTurn']),
        'attaches_to_opponents_pokemon: %s' % b(c['attachesToOpponentsPokemon']),
        'energy_type: %d' % c['energyType'],
        'provides: %s' % u8s(c['provides']),
        'methods: &[%s]' % ', '.join(lit(m) for m in c['methods']),
        'fossil_doll: %s' % b(c['fossilDoll']),
    ]
    out.append('    CardDef { %s },\n' % ', '.join(fields))
out.append('];\n')
open(os.path.join(GEN, 'cards.rs'), 'w').write(''.join(out))
print('generated', len(cards), 'cards')

for name, doc, rows in (('stage1', '(name, evolvesFrom) of every Stage 1 Pokémon card.', evolutions['stage1']),
                        ('evolutions', '(name, evolvesFrom) of every non-Basic Pokémon card.', evolutions['evolutions'])):
    const = 'ALL_STAGE1' if name == 'stage1' else 'ALL_EVOLUTIONS'
    out = ['// Generated by tools/gen_carddb.py. Do not edit.\n', '/// %s\n' % doc, 'pub static %s: &[(&str, &str)] = &[\n' % const]
    for n, f in rows:
        out.append('    (%s, %s),\n' % (lit(n), lit(f)))
    out.append('];\n')
    open(os.path.join(GEN, name + '.rs'), 'w').write(''.join(out))
    print('generated', len(rows), name, 'pairs')
